export interface Recipe {
  id: string
  name: string
  emoji: string
  tag: string         // 'Alta proteína' | 'Bajo carb' | 'Pre-entreno' | etc.
  time: number        // minutes
  cal: number
  prot: number
  carbs: number
  fat: number
  servings: number
  ingredients: { name: string; amount: string }[]
  steps: string[]
  category: 'Desayuno' | 'Almuerzo' | 'Cena' | 'Snack'
}

export const RECIPES: Recipe[] = [
  {
    id: 'bowl-proteico',
    name: 'Bowl proteico de pollo',
    emoji: '🍗',
    tag: 'Alta proteína',
    time: 25,
    cal: 520, prot: 48, carbs: 42, fat: 14,
    servings: 1,
    category: 'Almuerzo',
    ingredients: [
      { name: 'Pechuga de pollo', amount: '150g' },
      { name: 'Arroz integral cocido', amount: '150g' },
      { name: 'Brócoli', amount: '100g' },
      { name: 'Aceite de oliva', amount: '10ml' },
      { name: 'Ajo, sal, pimienta', amount: 'al gusto' },
    ],
    steps: [
      'Cuece el arroz integral según instrucciones del paquete.',
      'Sazona la pechuga con ajo, sal y pimienta. Cocina a fuego medio 6-7 min por lado.',
      'Cocina el brócoli al vapor 5 minutos.',
      'Arma el bowl con arroz de base, pollo en tiras y brócoli. Rocía con aceite de oliva.',
    ],
  },
  {
    id: 'omelette-espinaca',
    name: 'Omelette de claras y espinaca',
    emoji: '🍳',
    tag: 'Bajo carb',
    time: 10,
    cal: 220, prot: 28, carbs: 4, fat: 9,
    servings: 1,
    category: 'Desayuno',
    ingredients: [
      { name: 'Claras de huevo', amount: '200g (≈6 claras)' },
      { name: 'Espinaca fresca', amount: '50g' },
      { name: 'Tomate cherry', amount: '60g' },
      { name: 'Aceite de coco', amount: '5ml' },
      { name: 'Sal y orégano', amount: 'al gusto' },
    ],
    steps: [
      'Bate las claras con sal y orégano hasta que estén espumosas.',
      'Calienta el aceite en sartén antiadherente a fuego medio.',
      'Vierte las claras y agrega espinaca y tomates cherry partidos.',
      'Dobla el omelette cuando los bordes estén firmes. Sirve caliente.',
    ],
  },
  {
    id: 'salmon-esparragos',
    name: 'Salmón con espárragos al horno',
    emoji: '🐟',
    tag: 'Omega-3',
    time: 20,
    cal: 430, prot: 38, carbs: 6, fat: 28,
    servings: 1,
    category: 'Cena',
    ingredients: [
      { name: 'Filete de salmón', amount: '180g' },
      { name: 'Espárragos', amount: '150g' },
      { name: 'Aceite de oliva', amount: '15ml' },
      { name: 'Limón', amount: '½ unidad' },
      { name: 'Ajo en polvo, sal', amount: 'al gusto' },
    ],
    steps: [
      'Precalienta el horno a 200°C.',
      'Coloca el salmón y espárragos en bandeja. Rocía con aceite, limón y condimentos.',
      'Hornea 15-18 minutos hasta que el salmón esté cocido en el centro.',
    ],
  },
  {
    id: 'batido-proteico',
    name: 'Batido post-entreno',
    emoji: '🥤',
    tag: 'Post-entreno',
    time: 5,
    cal: 310, prot: 35, carbs: 30, fat: 5,
    servings: 1,
    category: 'Snack',
    ingredients: [
      { name: 'Proteína Whey vainilla', amount: '30g' },
      { name: 'Plátano maduro', amount: '100g' },
      { name: 'Leche descremada', amount: '250ml' },
      { name: 'Avena en hojuelas', amount: '30g' },
    ],
    steps: [
      'Coloca todos los ingredientes en la licuadora.',
      'Licúa 30 segundos hasta obtener consistencia suave.',
      'Consume dentro de los 30 min post-entrenamiento.',
    ],
  },
  {
    id: 'ensalada-atun',
    name: 'Ensalada de atún y quinoa',
    emoji: '🥗',
    tag: 'Ligero',
    time: 15,
    cal: 380, prot: 32, carbs: 38, fat: 10,
    servings: 1,
    category: 'Almuerzo',
    ingredients: [
      { name: 'Atún en agua', amount: '140g (1 lata)' },
      { name: 'Quinoa cocida', amount: '120g' },
      { name: 'Tomate', amount: '80g' },
      { name: 'Pepino', amount: '60g' },
      { name: 'Aceite de oliva', amount: '10ml' },
      { name: 'Limón, sal', amount: 'al gusto' },
    ],
    steps: [
      'Cuece la quinoa según instrucciones (2 partes agua : 1 quinoa, 15 min).',
      'Escurre el atún y desmenuza.',
      'Mezcla quinoa, atún, tomate y pepino en cubitos.',
      'Aliña con aceite de oliva, limón y sal.',
    ],
  },
  {
    id: 'tortilla-avena',
    name: 'Tortilla de avena proteica',
    emoji: '🫓',
    tag: 'Pre-entreno',
    time: 10,
    cal: 280, prot: 22, carbs: 28, fat: 8,
    servings: 1,
    category: 'Desayuno',
    ingredients: [
      { name: 'Avena en hojuelas', amount: '50g' },
      { name: 'Huevo entero', amount: '1 unidad (60g)' },
      { name: 'Claras de huevo', amount: '2 unidades (66g)' },
      { name: 'Leche (cualquier tipo)', amount: '50ml' },
      { name: 'Canela y stevia', amount: 'al gusto' },
    ],
    steps: [
      'Mezcla todos los ingredientes en un bowl hasta integrar.',
      'Vierte en sartén antiadherente a fuego bajo-medio.',
      'Cocina 3-4 min por lado. Sirve con fruta fresca.',
    ],
  },
  {
    id: 'pollo-camote',
    name: 'Pollo con camote y verduras',
    emoji: '🍠',
    tag: 'Volumen',
    time: 35,
    cal: 580, prot: 42, carbs: 58, fat: 14,
    servings: 1,
    category: 'Cena',
    ingredients: [
      { name: 'Pechuga de pollo', amount: '150g' },
      { name: 'Camote (batata)', amount: '200g' },
      { name: 'Zucchini', amount: '100g' },
      { name: 'Aceite de oliva', amount: '12ml' },
      { name: 'Pimentón, comino, sal', amount: 'al gusto' },
    ],
    steps: [
      'Corta el camote en cubos y asa al horno 200°C por 25 min.',
      'Saltea el pollo en cubos con aceite y condimentos 8-10 min.',
      'Agrega el zucchini en rodajas los últimos 5 minutos.',
      'Sirve junto al camote asado.',
    ],
  },
  {
    id: 'yogur-frutas',
    name: 'Yogur griego con frutas y granola',
    emoji: '🫙',
    tag: 'Rápido',
    time: 3,
    cal: 290, prot: 18, carbs: 38, fat: 6,
    servings: 1,
    category: 'Snack',
    ingredients: [
      { name: 'Yogur griego 0%', amount: '200g' },
      { name: 'Frutillas / arándanos', amount: '80g' },
      { name: 'Granola sin azúcar', amount: '25g' },
      { name: 'Miel', amount: '10g' },
    ],
    steps: [
      'Coloca el yogur en un bowl.',
      'Agrega las frutas y la granola encima.',
      'Rocía con miel. Listo en menos de 3 minutos.',
    ],
  },
  {
    id: 'avena-proteica',
    name: 'Avena proteica con plátano',
    emoji: '🥣',
    tag: 'Pre-entreno',
    time: 8,
    cal: 410, prot: 28, carbs: 58, fat: 8,
    servings: 1,
    category: 'Desayuno',
    ingredients: [
      { name: 'Avena', amount: '60g' },
      { name: 'Proteína whey vainilla', amount: '30g' },
      { name: 'Plátano', amount: '1 unidad' },
      { name: 'Leche descremada', amount: '200ml' },
      { name: 'Canela', amount: 'al gusto' },
    ],
    steps: [
      'Cocina la avena con la leche a fuego medio 3-4 minutos.',
      'Retira del fuego y deja entibiar 1 minuto.',
      'Mezcla la proteína whey hasta integrar.',
      'Sirve con plátano en rodajas y canela encima.',
    ],
  },
  {
    id: 'tostadas-palta-huevo',
    name: 'Tostadas de palta y huevo',
    emoji: '🥑',
    tag: 'Saludable',
    time: 10,
    cal: 380, prot: 18, carbs: 32, fat: 22,
    servings: 1,
    category: 'Desayuno',
    ingredients: [
      { name: 'Pan integral', amount: '2 rebanadas' },
      { name: 'Palta', amount: '½ unidad' },
      { name: 'Huevo', amount: '2 unidades' },
      { name: 'Sal, pimienta, merkén', amount: 'al gusto' },
    ],
    steps: [
      'Tuesta el pan integral.',
      'Fríe o pocha los huevos a tu gusto.',
      'Muele la palta y úntala sobre las tostadas.',
      'Coloca el huevo encima y sazona con sal, pimienta y merkén.',
    ],
  },
  {
    id: 'yogurt-frutos',
    name: 'Yogurt griego con frutos rojos',
    emoji: '🫐',
    tag: 'Snack',
    time: 3,
    cal: 220, prot: 20, carbs: 24, fat: 4,
    servings: 1,
    category: 'Snack',
    ingredients: [
      { name: 'Yogurt griego natural 0%', amount: '200g' },
      { name: 'Frutos rojos', amount: '80g' },
      { name: 'Almendras', amount: '15g' },
      { name: 'Miel', amount: '5g' },
    ],
    steps: [
      'Sirve el yogurt griego en un bowl.',
      'Agrega los frutos rojos y almendras picadas.',
      'Rocía con un hilo de miel.',
    ],
  },
  {
    id: 'wrap-pollo',
    name: 'Wrap de pollo y verduras',
    emoji: '🌯',
    tag: 'Alta proteína',
    time: 15,
    cal: 450, prot: 40, carbs: 38, fat: 14,
    servings: 1,
    category: 'Almuerzo',
    ingredients: [
      { name: 'Tortilla integral', amount: '1 unidad' },
      { name: 'Pechuga de pollo', amount: '130g' },
      { name: 'Lechuga, tomate, zanahoria', amount: '100g' },
      { name: 'Yogurt griego (aderezo)', amount: '30g' },
      { name: 'Mostaza', amount: 'al gusto' },
    ],
    steps: [
      'Cocina la pechuga a la plancha y córtala en tiras.',
      'Mezcla el yogurt con mostaza para el aderezo.',
      'Rellena la tortilla con verduras, pollo y aderezo.',
      'Enrolla firme y corta por la mitad.',
    ],
  },
  {
    id: 'ensalada-atun',
    name: 'Ensalada de atún y garbanzos',
    emoji: '🥗',
    tag: 'Alta proteína',
    time: 10,
    cal: 390, prot: 34, carbs: 30, fat: 14,
    servings: 1,
    category: 'Almuerzo',
    ingredients: [
      { name: 'Atún en agua', amount: '140g' },
      { name: 'Garbanzos cocidos', amount: '100g' },
      { name: 'Tomate, pepino, cebolla', amount: '120g' },
      { name: 'Aceite de oliva', amount: '10ml' },
      { name: 'Limón, sal', amount: 'al gusto' },
    ],
    steps: [
      'Escurre el atún y los garbanzos.',
      'Pica las verduras en cubos pequeños.',
      'Mezcla todo en un bowl.',
      'Aliña con aceite de oliva, limón y sal.',
    ],
  },
  {
    id: 'pollo-quinoa',
    name: 'Pollo con quinoa y palta',
    emoji: '🍗',
    tag: 'Balanceado',
    time: 25,
    cal: 540, prot: 44, carbs: 46, fat: 18,
    servings: 1,
    category: 'Almuerzo',
    ingredients: [
      { name: 'Pechuga de pollo', amount: '150g' },
      { name: 'Quinoa cocida', amount: '150g' },
      { name: 'Palta', amount: '½ unidad' },
      { name: 'Espinaca', amount: '50g' },
      { name: 'Aceite de oliva, limón', amount: 'al gusto' },
    ],
    steps: [
      'Cuece la quinoa según instrucciones.',
      'Cocina el pollo a la plancha sazonado.',
      'Sirve la quinoa de base con espinaca fresca.',
      'Agrega pollo en tiras y palta en láminas. Aliña.',
    ],
  },
  {
    id: 'carne-pure-camote',
    name: 'Carne magra con puré de camote',
    emoji: '🍠',
    tag: 'Post-entreno',
    time: 30,
    cal: 510, prot: 42, carbs: 44, fat: 16,
    servings: 1,
    category: 'Almuerzo',
    ingredients: [
      { name: 'Posta o filete de vacuno', amount: '150g' },
      { name: 'Camote', amount: '200g' },
      { name: 'Poroto verde', amount: '100g' },
      { name: 'Aceite de oliva', amount: '10ml' },
      { name: 'Sal, pimienta', amount: 'al gusto' },
    ],
    steps: [
      'Cuece el camote y hazlo puré con un poco de aceite.',
      'Cocina la carne a la plancha al punto deseado.',
      'Saltea los porotos verdes al vapor.',
      'Sirve la carne con el puré y las verduras.',
    ],
  },
  {
    id: 'tortilla-avena',
    name: 'Tortilla de avena salada',
    emoji: '🫓',
    tag: 'Pre-entreno',
    time: 12,
    cal: 340, prot: 26, carbs: 34, fat: 10,
    servings: 1,
    category: 'Desayuno',
    ingredients: [
      { name: 'Avena', amount: '40g' },
      { name: 'Huevo', amount: '1 unidad' },
      { name: 'Claras de huevo', amount: '100g' },
      { name: 'Queso fresco', amount: '30g' },
      { name: 'Sal, orégano', amount: 'al gusto' },
    ],
    steps: [
      'Licúa la avena con el huevo y las claras.',
      'Vierte en sartén antiadherente caliente.',
      'Agrega queso fresco en el centro.',
      'Dobla como tortilla y cocina 2 min por lado.',
    ],
  },
  {
    id: 'salmon-arroz',
    name: 'Salmón teriyaki con arroz',
    emoji: '🍣',
    tag: 'Omega-3',
    time: 22,
    cal: 560, prot: 40, carbs: 52, fat: 20,
    servings: 1,
    category: 'Cena',
    ingredients: [
      { name: 'Filete de salmón', amount: '170g' },
      { name: 'Arroz integral cocido', amount: '150g' },
      { name: 'Salsa teriyaki baja en azúcar', amount: '20ml' },
      { name: 'Brócoli', amount: '100g' },
      { name: 'Sésamo', amount: 'al gusto' },
    ],
    steps: [
      'Marina el salmón en teriyaki 10 minutos.',
      'Cocínalo a la plancha 4 min por lado.',
      'Cuece el brócoli al vapor.',
      'Sirve sobre arroz con sésamo encima.',
    ],
  },
  {
    id: 'sopa-verduras-pollo',
    name: 'Sopa de verduras con pollo',
    emoji: '🍲',
    tag: 'Bajo cal',
    time: 30,
    cal: 260, prot: 28, carbs: 20, fat: 6,
    servings: 1,
    category: 'Cena',
    ingredients: [
      { name: 'Pechuga de pollo', amount: '120g' },
      { name: 'Zanahoria, apio, zapallo', amount: '200g' },
      { name: 'Caldo de verduras', amount: '400ml' },
      { name: 'Cilantro, sal', amount: 'al gusto' },
    ],
    steps: [
      'Hierve el caldo con las verduras picadas 15 min.',
      'Agrega el pollo en cubos y cocina 10 min más.',
      'Ajusta sal y sirve con cilantro fresco.',
    ],
  },
  {
    id: 'batido-proteico',
    name: 'Batido proteico post-entreno',
    emoji: '🥤',
    tag: 'Post-entreno',
    time: 3,
    cal: 320, prot: 35, carbs: 38, fat: 4,
    servings: 1,
    category: 'Snack',
    ingredients: [
      { name: 'Proteína whey', amount: '30g' },
      { name: 'Plátano', amount: '1 unidad' },
      { name: 'Avena', amount: '30g' },
      { name: 'Leche descremada', amount: '300ml' },
    ],
    steps: [
      'Agrega todos los ingredientes a la licuadora.',
      'Licúa 30 segundos hasta homogéneo.',
      'Sirve inmediatamente después de entrenar.',
    ],
  },
  {
    id: 'huevos-revueltos-pavo',
    name: 'Huevos revueltos con pavo',
    emoji: '🍳',
    tag: 'Alta proteína',
    time: 10,
    cal: 300, prot: 32, carbs: 6, fat: 16,
    servings: 1,
    category: 'Desayuno',
    ingredients: [
      { name: 'Huevo', amount: '2 unidades' },
      { name: 'Claras de huevo', amount: '100g' },
      { name: 'Pechuga de pavo', amount: '60g' },
      { name: 'Cebollín', amount: 'al gusto' },
    ],
    steps: [
      'Bate los huevos con las claras.',
      'Saltea el pavo en cubos 2 minutos.',
      'Agrega los huevos y revuelve a fuego bajo.',
      'Termina con cebollín picado.',
    ],
  },
  {
    id: 'lentejas-guiso',
    name: 'Guiso de lentejas con verduras',
    emoji: '🍛',
    tag: 'Vegetariano',
    time: 35,
    cal: 420, prot: 24, carbs: 62, fat: 8,
    servings: 1,
    category: 'Almuerzo',
    ingredients: [
      { name: 'Lentejas', amount: '80g (secas)' },
      { name: 'Zanahoria, cebolla, pimentón', amount: '150g' },
      { name: 'Arroz integral', amount: '50g' },
      { name: 'Aceite de oliva, comino', amount: 'al gusto' },
    ],
    steps: [
      'Sofríe cebolla, zanahoria y pimentón.',
      'Agrega lentejas y agua, cocina 25 min.',
      'Añade el arroz y cocina 15 min más.',
      'Sazona con comino y sal.',
    ],
  },
  {
    id: 'ensalada-pollo-cesar',
    name: 'Ensalada César fit de pollo',
    emoji: '🥗',
    tag: 'Bajo carb',
    time: 15,
    cal: 360, prot: 38, carbs: 12, fat: 18,
    servings: 1,
    category: 'Cena',
    ingredients: [
      { name: 'Pechuga de pollo', amount: '140g' },
      { name: 'Lechuga romana', amount: '120g' },
      { name: 'Yogurt griego (aderezo)', amount: '40g' },
      { name: 'Queso parmesano', amount: '15g' },
      { name: 'Mostaza, ajo, limón', amount: 'al gusto' },
    ],
    steps: [
      'Cocina el pollo a la plancha y córtalo.',
      'Mezcla yogurt, mostaza, ajo y limón para el aderezo.',
      'Baña la lechuga con el aderezo.',
      'Agrega pollo y parmesano rallado.',
    ],
  },
  {
    id: 'panqueques-avena',
    name: 'Panqueques de avena y plátano',
    emoji: '🥞',
    tag: 'Pre-entreno',
    time: 15,
    cal: 380, prot: 24, carbs: 52, fat: 8,
    servings: 1,
    category: 'Desayuno',
    ingredients: [
      { name: 'Avena', amount: '50g' },
      { name: 'Plátano', amount: '1 unidad' },
      { name: 'Huevo', amount: '1 unidad' },
      { name: 'Claras de huevo', amount: '100g' },
      { name: 'Polvos de hornear', amount: '1 cdta' },
    ],
    steps: [
      'Licúa todos los ingredientes hasta formar una masa.',
      'Calienta sartén antiadherente a fuego medio.',
      'Vierte porciones y cocina 2 min por lado.',
      'Sirve con fruta fresca encima.',
    ],
  },
  {
    id: 'merluza-verduras',
    name: 'Merluza al horno con verduras',
    emoji: '🐟',
    tag: 'Bajo cal',
    time: 25,
    cal: 290, prot: 36, carbs: 18, fat: 8,
    servings: 1,
    category: 'Cena',
    ingredients: [
      { name: 'Filete de merluza', amount: '180g' },
      { name: 'Zapallo italiano, pimentón', amount: '200g' },
      { name: 'Aceite de oliva', amount: '10ml' },
      { name: 'Ajo, limón, perejil', amount: 'al gusto' },
    ],
    steps: [
      'Precalienta el horno a 200°C.',
      'Coloca la merluza y verduras en una fuente.',
      'Aliña con aceite, ajo, limón y sal.',
      'Hornea 18-20 minutos. Sirve con perejil.',
    ],
  },
  {
    id: 'colacion-frutos-secos',
    name: 'Mix de frutos secos y fruta',
    emoji: '🥜',
    tag: 'Snack',
    time: 2,
    cal: 240, prot: 8, carbs: 22, fat: 15,
    servings: 1,
    category: 'Snack',
    ingredients: [
      { name: 'Almendras y nueces', amount: '25g' },
      { name: 'Manzana', amount: '1 unidad' },
      { name: 'Pasas', amount: '15g' },
    ],
    steps: [
      'Combina los frutos secos con las pasas.',
      'Acompaña con la manzana en gajos.',
      'Ideal como colación de media tarde.',
    ],
  },
  {
    id: 'arroz-integral-pollo-curry',
    name: 'Pollo al curry con arroz',
    emoji: '🍛',
    tag: 'Balanceado',
    time: 25,
    cal: 520, prot: 42, carbs: 50, fat: 15,
    servings: 1,
    category: 'Almuerzo',
    ingredients: [
      { name: 'Pechuga de pollo', amount: '150g' },
      { name: 'Arroz integral cocido', amount: '150g' },
      { name: 'Leche de coco light', amount: '80ml' },
      { name: 'Curry en polvo', amount: '1 cda' },
      { name: 'Cebolla, ajo', amount: 'al gusto' },
    ],
    steps: [
      'Sofríe cebolla y ajo, agrega el pollo en cubos.',
      'Añade curry y leche de coco, cocina 10 min.',
      'Deja reducir la salsa a fuego bajo.',
      'Sirve sobre el arroz integral.',
    ],
  },
  {
    id: 'tacos-fit-pavo',
    name: 'Tacos fit de pavo',
    emoji: '🌮',
    tag: 'Alta proteína',
    time: 18,
    cal: 440, prot: 38, carbs: 40, fat: 14,
    servings: 1,
    category: 'Cena',
    ingredients: [
      { name: 'Carne molida de pavo', amount: '150g' },
      { name: 'Tortillas de maíz', amount: '3 unidades' },
      { name: 'Lechuga, tomate, cebolla morada', amount: '100g' },
      { name: 'Palta', amount: '¼ unidad' },
      { name: 'Comino, pimentón', amount: 'al gusto' },
    ],
    steps: [
      'Cocina el pavo con comino y pimentón.',
      'Calienta las tortillas.',
      'Rellena con pavo, verduras y palta.',
      'Sirve con limón al gusto.',
    ],
  },
  {
    id: 'porridge-proteico',
    name: 'Porridge de quinoa proteico',
    emoji: '🥣',
    tag: 'Vegetariano',
    time: 15,
    cal: 400, prot: 26, carbs: 54, fat: 9,
    servings: 1,
    category: 'Desayuno',
    ingredients: [
      { name: 'Quinoa', amount: '60g' },
      { name: 'Leche de almendras', amount: '250ml' },
      { name: 'Proteína vegetal vainilla', amount: '25g' },
      { name: 'Arándanos', amount: '60g' },
      { name: 'Canela, semillas de chía', amount: 'al gusto' },
    ],
    steps: [
      'Cocina la quinoa con la leche de almendras 12 min.',
      'Retira del fuego e integra la proteína.',
      'Sirve con arándanos, chía y canela.',
    ],
  },
]

export function filterRecipes(query: string, cat?: string): Recipe[] {
  return RECIPES.filter(r => {
    const matchCat = !cat || r.category === cat
    const matchQ = !query || r.name.toLowerCase().includes(query.toLowerCase()) || r.tag.toLowerCase().includes(query.toLowerCase())
    return matchCat && matchQ
  })
}
